In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline
#always include these

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#always include these

In [3]:
from math import sqrt

In [4]:
print ("shift + enter")

shift + enter


In [5]:
2 + 5

7

In [6]:
x = 1
y = 3 + x
y

4

In [7]:
while True:
    x = 1

KeyboardInterrupt: 

Typing text because this is a markdown cell

<h1> This is a heading</h1>
<p> and paragraph in html, markup! </p>

# Heading markdown

In [8]:
u = np.array([2, -7, 1])
v = np.array([-3, 0, 4])

A = np.array([[1, 2, 0], [3, -1, 4]])
B = np.array([[2, -1], [1, 0], [-3, 4]])

In [9]:
u + v #A

array([-1, -7,  5])

In [10]:
-3 * u #B

array([-6, 21, -3])

In [11]:
np.dot(u, v) #C
# can also do u.T.dot(v)

-2

In [12]:
u.dot(u) #D

54

In [13]:
np.sqrt(u.dot(u)) #E

7.3484692283495345

In [14]:
u * v #F

array([-6,  0,  4])

In [15]:
A + A #G

array([[ 2,  4,  0],
       [ 6, -2,  8]])

In [16]:
A + u #H error message should happen

array([[ 3, -5,  1],
       [ 5, -8,  5]])

In [17]:
10 * A #I

array([[ 10,  20,   0],
       [ 30, -10,  40]])

In [18]:
np.dot(A, v) #J

array([-3,  7])

In [19]:
np.dot(A, B) #K

array([[ 4, -1],
       [-7, 13]])

In [20]:
A.transpose() #L

array([[ 1,  3],
       [ 2, -1],
       [ 0,  4]])

In [21]:
A.dot(A.transpose()) #M

array([[ 5,  1],
       [ 1, 26]])

In [22]:
np.dot(A.transpose(), A) #N

array([[10, -1, 12],
       [-1,  5, -4],
       [12, -4, 16]])

In [23]:
np.min(u) #O

-7

In [24]:
np.argmin(u) #P

1

In [25]:
np.mean(u) #Q

-1.3333333333333333

In [26]:
np.cumsum(u)

array([ 2, -5, -4])

In [27]:
np.cumsum(A)

array([1, 3, 3, 6, 5, 9])

In [28]:
#def cumsum1(A):
    #if null return A
    #temp = A.pop(0)
    #return cumsum1(A) + temp

def cumsum1(A):
    total = 0
    newList = []
    for x in A:
        total += x
        newList.append(total)
    return newList

In [29]:
x = list(range(1, 1000))

cumsum1(x)

%timeit cumsum1(x)
%timeit np.cumsum(x)

42.7 µs ± 262 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
27.8 µs ± 164 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
